name: Deploy to EC2 Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/app"
          overwrite: true

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app

            IMAGE_TAG="${{ github.sha }}"

            docker build -t hello-k8s:$IMAGE_TAG .

            minikube image load hello-k8s:$IMAGE_TAG

            sed -i "s|image: hello-k8s:.*|image: hello-k8s:$IMAGE_TAG|g" k8s.yaml

            kubectl apply -f k8s.yaml

            kubectl rollout status deployment/hello-k8s-deployment